// Enums for status and roles
export enum UserRole {
  PATIENT = 'PATIENT',
  DOCTOR = 'DOCTOR',
  LAB_TECHNICIAN = 'LAB_TECHNICIAN',
  ADMIN = 'ADMIN'
}

export enum AppointmentStatus {
  SCHEDULED = 'SCHEDULED',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED'
}

export enum LedgerAction {
  UPLOAD_RECORD = 'UPLOAD_RECORD',
  GENERATE_KEY = 'GENERATE_KEY',
  AUTO_GENERATE_KEY = 'AUTO_GENERATE_KEY',
  ACCESS_DATA = 'ACCESS_DATA',
  REVOKE_ACCESS = 'REVOKE_ACCESS',
  REQUEST_ACCESS = 'REQUEST_ACCESS',
  APPROVE_ACCESS = 'APPROVE_ACCESS',
  REJECT_ACCESS = 'REJECT_ACCESS',
  EMERGENCY_ACCESS = 'EMERGENCY_ACCESS',
  REGISTER_PATIENT = 'REGISTER_PATIENT',
  UPDATE_EMERGENCY_SETTINGS = 'UPDATE_EMERGENCY_SETTINGS',
  LAB_REQUEST_SUBMITTED = 'LAB_REQUEST_SUBMITTED',
  LAB_REQUEST_APPROVED = 'LAB_REQUEST_APPROVED',
  LAB_REQUEST_REJECTED = 'LAB_REQUEST_REJECTED'
}

// Database Table: Users
export interface User {
  id: string;
  name: string;
  role: UserRole;
  phoneNumber?: string; // For patients to link accounts
  hospitalName?: string; // Only for doctors/lab
  specialty?: string; // Cardiology, Radiology, etc.
  location?: { lat: number; lng: number }; // Simulation for Geo-fencing
  emergencyInfo?: string; // Vital info like allergies, blood type
  age?: number;
  gender?: 'Male' | 'Female' | 'Other';
}

// Database Table: MedicalRecords (Metadata only)
export interface MedicalRecord {
  id: string;
  patientId: string;
  title: string;
  description: string; // Encrypted content simulation
  fileName?: string; // Name of the actual file
  billFileName?: string; // Name of the associated bill
  fileType: 'PDF' | 'DICOM' | 'LAB';
  dateCreated: string;
  dataHash: string; // The fingerprint
  fileUrl?: string; // Local URL for previewing real uploads
  isEmergencyAccessible?: boolean; // Can this be seen in emergency override?
  followUpDate?: string; // ISO Date string for reminders
}

// Temporary Holding for Lab Uploads
export interface LabRequest {
  id: string;
  patientId: string;
  labTechId: string;
  labName: string;
  title: string;
  description: string;
  reportFileName: string;
  billFileName: string;
  fileType: 'PDF' | 'DICOM' | 'LAB';
  status: 'PENDING' | 'APPROVED' | 'REJECTED';
  dateSubmitted: string;
}

// Database Table: Appointments
export interface Appointment {
  id: string;
  patientId: string;
  doctorId: string;
  doctorName: string;
  hospitalName: string;
  date: string; // ISO String
  durationMinutes: number;
  status: AppointmentStatus;
  accessRequestStatus?: 'PENDING' | 'APPROVED' | 'REJECTED';
}

// Database Table: AccessKeys
export interface AccessKey {
  code: string; // 6-digit OTP
  appointmentId: string;
  patientId: string;
  generatedAt: string;
  expiresAt: string;
  isActive: boolean;
  isAutoGenerated: boolean;
}

// Blockchain / Ledger Structure
export interface LedgerBlock {
  index: number;
  timestamp: string;
  action: LedgerAction;
  details: string; // Summary of what happened
  dataHash: string; // Hash of the record or transaction
  previousHash: string;
  blockHash: string;
}

export interface AppState {
  currentUser: User | null;
  users: User[];
  records: MedicalRecord[];
  appointments: Appointment[];
  accessKeys: AccessKey[];
  labRequests: LabRequest[];
  ledger: LedgerBlock[];
}